### ISSUE TITLE
Safari compatibility?

### ISSUE THREAD

**Issue by llnnse** [sean-public/RecipeFilter#20]
Do you have any plans on moving your recipe filter extension to other browsers, too?

**Comment by sean-public** [comment]
Yes! As announced yesterday at WWDC:

> ...Safari for Mac is adding support for the popular WebExtensions API used by Chrome, Firefox, and Edge, making it easy for extension developers to work with Safari, and distribute through the Mac App Store. ([link to more](https://www.apple.com/newsroom/2020/06/apple-reveals-new-developer-technologies-to-foster-the-next-generation-of-apps/))

[This extension was specifically demoed in the Keynote by Beth Dakin](https://www.youtube.com/watch?v=Kwh2y6VkzoA), but that was done using a preview build of Safari and XCode by Apple (they asked my permission first), so I still need to do the same porting on my own to get it working on the new version of Safari. I think it will be released in the fall and I intend to have the extension working by then so everyone can use it right away.

In the past, extensions could be distributed on their own but a couple years ago, Apple required that they come bundled as part of an app. Since there's no "app" part to Recipe Filter, I never thought of making a Safari version until now.

**Comment by sebastianludwig** [comment]
Any updates on this? Or does "closed" mean that the plans changed and that it won't come to Safari any time soon?

**Comment by blackketter** [comment]
thanks, @sean-public, really looking forward to this on safari.  Any updates?

**Comment by StarrGazr** [comment]
Please add this! I can't stand trying to read recipes on the web! I saw this in the Keynote and I REALLY want this!
